### ISSUE TITLE
add specification to read me

### ISSUE THREAD

**Issue by ostat** [CullenJWebb/Cullenect-Labels#2]
To make implementation of the labels and receiving holes easier, could you please add some details about the read me about the specifications. 
What dimensions should the label be including each of the heights for the click mechanism.
What dimensions should the receiving hole be, including the click mechanism, and the amount of expected clearance.

If we are not yet sure of the dimensions this can serve as a starting point to work from to ensure consistency across implementations.

**Comment by CullenJWebb** [comment]
Good thinking, I'll get on that.

**Comment by ostat** [comment]
With regards to the specifications. I notice that the two click ribs on V2 are at different heights. Which side should go to the front/bottom?

This does mean that a label printed to go on the back of a bin, wont work on the front (as the same side will always be on the inside). The generator might need support for rotating the text.

**Comment by CullenJWebb** [comment]
That was unintentional and left over from testing. It's been hotfixed, they should both by the lower height.

**Comment by CullenJWebb** [comment]
While I have your ear, do you have a preferred way to create dimensioned drawings from STL files?

I am creating the specifications for the readme but I haven't found a good way to create the drawings.

**Comment by ostat** [comment]
you can add dimensions to a openscad drawing. But its a pain and manual. 
I do it in Gridfinity extended, That that is mostly so people know what size they are generating.

I would prob use a third party tool, like onshape. In there you can create a sketch that will look nice and have all the detail.

**Comment by CullenJWebb** [comment]
@ostat All set on those specifications, I've updated the readme. Please take a look and let me know if there are any details missing.

Thanks!

**Comment by darsor** [comment]
The drawings in the README were very useful. I also noticed the height difference in the sockets (which doesn't match the drawings), which is still present on main.
